<?php


namespace Commune\Chatlog\SocketIO\DTO;


use Commune\Blueprint\Framework\Auth\Supervise;
use Commune\Support\Message\AbsMessage;

/**
 * @property-read string $id
 * @property-read string $name
 * @property-read int $level
 */
class UserInfo extends AbsMessage
{

    public static function stub(): array
    {
        return [
            'id' => '',
            'name' => '',
            'level' => Supervise::GUEST,
        ];
    }

    public static function validate(array $data): ? string /* errorMsg */
    {
        return parent::validate($data); // TODO: Change the autogenerated stub
    }

    public static function relations(): array
    {
        return [];
    }

    public function isEmpty(): bool
    {
        return false;
    }


}