<?php


namespace Commune\Chatlog\SocketIO\Protocal;


use Commune\Support\Message\AbsMessage;

/**
 * @property-read string $id
 * @property-read string $name
 * @property-read string $token
 * @property-read bool $authorized
 * @property-read bool $supervise
 */
class UserInfo extends AbsMessage
{

    public static function stub(): array
    {
        return [
            'id' => '',
            'name' => '',
            'token' => '',
            'authorized' => false,
            'supervise' => false,
        ];
    }

    public static function validate(array $data): ? string /* errorMsg */
    {
        return parent::validate($data); // TODO: Change the autogenerated stub
    }

    public static function relations(): array
    {
        return [];
    }

    public function isEmpty(): bool
    {
        return false;
    }


}